### PR TITLE
Use StaticInteger instead of StaticInt and add tests for static util functions

### PR DESCRIPTION
**Pull request by oschulz**
Follow-up to #115 .

We should use `StaticInteger` instead of `StaticInt` for argument types.

Also adds tests for the new functions in static.jl.

### CODE REVIEW

**Comment by oschulz** [comment]
Tests fixed.

**Review by theogf — APPROVED** [review]
Nice, it just needs a version bump

**Review by cscherrer — APPROVED** [review]

**Comment by oschulz** [comment]
Added version bump.

**Comment by oschulz** [comment]
Merci @theogf !

**Comment by oschulz** [comment]
Next on the agenda will the polishing up the transport framework and turning DistributionMeasures.jl into a MeasureBase.jl Pkg-extension (DistributionMeasures.jl itself will become deprecated).

**Pull request merged**
