### PR TITLE
Improve transport implementation and add product support

### PR DESCRIPTION
**Pull request by oschulz**
Replaces #95

### CODE REVIEW

**Comment by cscherrer** [comment]
Some strange errors:
```
Test Summary: | Pass  Total
getdof        |   47     47
Internal error: encountered unexpected error in runtime:
MethodError(f=Core.Compiler.widenconst, args=(:(:base),), world=0x00000000000011c0)
jl_method_error_bare at /buildworker/worker/package_linux64/build/src/gf.c:1821
jl_method_error at /buildworker/worker/package_linux64/build/src/gf.c:1839
jl_lookup_generic_ at /buildworker/worker/package_linux64/build/src/gf.c:2410 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2425
getfield_elim_pass! at ./compiler/ssair/passes.jl:642
run_passes at ./compiler/optimize.jl:311
optimize at ./compiler/optimize.jl:296 [inlined]
_typeinf at ./compiler/typeinfer.jl:255
typeinf at ./compiler/typeinfer.jl:209
typeinf_ext at ./compiler/typeinfer.jl:909
typeinf_ext_toplevel at ./compiler/typeinfer.jl:942
typeinf_ext_toplevel at ./compiler/typeinfer.jl:938
```

**Comment by cscherrer** [comment]
It looks like this line
```julia
test_transport(2.2 * ν0, 2.2 * μ0)
```
leads to things like
```julia
NoTransportOrigin{NoTransportOrigin{NoTransportOrigin{NoTransportOrigin{NoTransportOrigin{...
```

**Comment by oschulz** [comment]
Hm, did I mess something up when rebasing this?

**Comment by cscherrer** [comment]
> Hm, did I mess something up when rebasing this?

Not sure yet what went wrong

**Review by cscherrer — APPROVED** [review]

**Pull request merged**
